/**
 * Hospital Seed Data - ALL Nepal Snakebite Treatment Centers
 * Based on EDCD National Guidelines and Provincial Health Data
 * Source: EDCD reports 88 snakebite treatment centers nationwide (2078/79)
 */

import { prisma } from '../../src/client.js';

// Comprehensive list of snakebite treatment centers across Nepal
// Based on EDCD official list (88 centers) + Provincial Health data
const hospitals = [
  // ==================== BAGMATI PROVINCE (11 centers) ====================
  {
    name: 'Bharatpur Hospital',
    address: 'Bharatpur-10, Chitwan',
    municipality: 'Bharatpur',
    ward: 10,
    district: 'Chitwan',
    province: 'Bagmati',
    latitude: 27.6831,
    longitude: 84.4342,
    phone: '056-521777',
    emergencyPhone: '056-521777',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Bir Hospital (National Trauma Center)',
    address: 'Mahabouddha, Kathmandu',
    municipality: 'Kathmandu',
    ward: 1,
    district: 'Kathmandu',
    province: 'Bagmati',
    latitude: 27.7042,
    longitude: 85.3138,
    phone: '01-4221119',
    emergencyPhone: '01-4221119',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
    notes: 'National referral center for trauma and emergency cases. Call to confirm current antivenom availability.',
  },
  {
    name: 'Tribhuvan University Teaching Hospital (TUTH)',
    address: 'Maharajgunj, Kathmandu',
    municipality: 'Kathmandu',
    district: 'Kathmandu',
    province: 'Bagmati',
    latitude: 27.7357,
    longitude: 85.3281,
    phone: '01-4412303',
    emergencyPhone: '01-4412707',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Patan Hospital (Patan Academy of Health Sciences)',
    address: 'Lagankhel, Lalitpur',
    municipality: 'Lalitpur',
    district: 'Lalitpur',
    province: 'Bagmati',
    latitude: 27.6694,
    longitude: 85.3264,
    phone: '01-5522295',
    emergencyPhone: '01-5522266',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Kanti Children\'s Hospital',
    address: 'Maharajgunj, Kathmandu',
    municipality: 'Kathmandu',
    district: 'Kathmandu',
    province: 'Bagmati',
    latitude: 27.7380,
    longitude: 85.3320,
    phone: '01-4411550',
    emergencyPhone: '01-4411550',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'SPECIALIZED',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Sukraraj Tropical and Infectious Disease Hospital',
    address: 'Teku, Kathmandu',
    municipality: 'Kathmandu',
    district: 'Kathmandu',
    province: 'Bagmati',
    latitude: 27.6952,
    longitude: 85.3048,
    phone: '01-4253396',
    emergencyPhone: '01-4253396',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'SPECIALIZED',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
    notes: 'Specialized infectious disease hospital',
  },
  {
    name: 'Sindhuli District Hospital',
    address: 'Sindhulimadi, Sindhuli',
    municipality: 'Sindhulimadi',
    district: 'Sindhuli',
    province: 'Bagmati',
    latitude: 27.2567,
    longitude: 85.9679,
    phone: '047-520076',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Nepal Police Hospital, Dudhauli',
    address: 'Dudhauli, Sindhuli',
    municipality: 'Dudhauli',
    district: 'Sindhuli',
    province: 'Bagmati',
    latitude: 27.2781,
    longitude: 85.8542,
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'SPECIALIZED',
    antivenomStatus: 'AVAILABLE',
    source: 'Bagmati_Provincial_Health',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'POLICE',
    status: 'ACTIVE',
  },
  {
    name: 'Hetauda Hospital',
    address: 'Hetauda, Makwanpur',
    municipality: 'Hetauda',
    district: 'Makwanpur',
    province: 'Bagmati',
    latitude: 27.4328,
    longitude: 85.0275,
    phone: '057-520133',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Nuwakot District Hospital',
    address: 'Bidur, Nuwakot',
    municipality: 'Bidur',
    district: 'Nuwakot',
    province: 'Bagmati',
    latitude: 27.9417,
    longitude: 85.2611,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dhading District Hospital',
    address: 'Dhading Besi, Dhading',
    municipality: 'Dhading Besi',
    district: 'Dhading',
    province: 'Bagmati',
    latitude: 27.8717,
    longitude: 84.9083,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== KOSHI PROVINCE (10 centers) ====================
  {
    name: 'BP Koirala Institute of Health Sciences (BPKIHS)',
    address: 'Dharan, Sunsari',
    municipality: 'Dharan',
    district: 'Sunsari',
    province: 'Koshi',
    latitude: 26.8124,
    longitude: 87.2845,
    phone: '025-525555',
    emergencyPhone: '025-525555',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Koshi Hospital',
    address: 'Biratnagar, Morang',
    municipality: 'Biratnagar',
    district: 'Morang',
    province: 'Koshi',
    latitude: 26.4525,
    longitude: 87.2718,
    phone: '021-525555',
    emergencyPhone: '021-525555',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    ambulanceAvailable: true,
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Birat Medical College Teaching Hospital',
    address: 'Tank Road, Biratnagar',
    municipality: 'Biratnagar',
    district: 'Morang',
    province: 'Koshi',
    latitude: 26.4603,
    longitude: 87.2835,
    phone: '021-520333',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'PRIVATE',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
  },
  {
    name: 'Nobel Hospital',
    address: 'Biratnagar, Morang',
    municipality: 'Biratnagar',
    district: 'Morang',
    province: 'Koshi',
    latitude: 26.4582,
    longitude: 87.2756,
    phone: '021-530333',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    antivenomStatus: 'AVAILABLE',
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
  },
  {
    name: 'Army Hospital Itahari',
    address: 'Itahari, Sunsari',
    municipality: 'Itahari',
    district: 'Sunsari',
    province: 'Koshi',
    latitude: 26.6709,
    longitude: 87.2735,
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'SPECIALIZED',
    antivenomStatus: 'AVAILABLE',
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'ARMY',
    status: 'ACTIVE',
  },
  {
    name: 'Katari District Hospital',
    address: 'Katari, Udayapur',
    municipality: 'Katari',
    district: 'Udayapur',
    province: 'Koshi',
    latitude: 26.9967,
    longitude: 86.9817,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Damak Hospital',
    address: 'Damak, Jhapa',
    municipality: 'Damak',
    district: 'Jhapa',
    province: 'Koshi',
    latitude: 26.6598,
    longitude: 87.7036,
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'Koshi_Provincial_Health',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Mechi Zonal Hospital',
    address: 'Bhadrapur, Jhapa',
    municipality: 'Bhadrapur',
    district: 'Jhapa',
    province: 'Koshi',
    latitude: 26.5467,
    longitude: 88.0946,
    phone: '023-462262',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dhankuta District Hospital',
    address: 'Dhankuta',
    municipality: 'Dhankuta',
    district: 'Dhankuta',
    province: 'Koshi',
    latitude: 26.9843,
    longitude: 87.3430,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Sankhuwasabha District Hospital',
    address: 'Khandbari, Sankhuwasabha',
    municipality: 'Khandbari',
    district: 'Sankhuwasabha',
    province: 'Koshi',
    latitude: 27.3666,
    longitude: 87.2180,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== MADHESH PROVINCE (12 centers) ====================
  {
    name: 'Janakpur Provincial Hospital',
    address: 'Janakpur, Dhanusha',
    municipality: 'Janakpur',
    district: 'Dhanusha',
    province: 'Madhesh',
    latitude: 26.7288,
    longitude: 85.9244,
    phone: '041-520133',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Gajendra Narayan Singh Hospital',
    address: 'Rajbiraj, Saptari',
    municipality: 'Rajbiraj',
    district: 'Saptari',
    province: 'Madhesh',
    latitude: 26.5439,
    longitude: 86.7428,
    phone: '031-520133',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Narayani Hospital',
    address: 'Birgunj, Parsa',
    municipality: 'Birgunj',
    district: 'Parsa',
    province: 'Madhesh',
    latitude: 27.0104,
    longitude: 84.8767,
    phone: '051-522111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Janaki Medical College',
    address: 'Janakpur, Dhanusha',
    municipality: 'Janakpur',
    district: 'Dhanusha',
    province: 'Madhesh',
    latitude: 26.7356,
    longitude: 85.9222,
    phone: '041-520133',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
  },
  {
    name: 'Siraha District Hospital',
    address: 'Siraha',
    municipality: 'Siraha',
    district: 'Siraha',
    province: 'Madhesh',
    latitude: 26.6546,
    longitude: 86.2082,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Rautahat District Hospital',
    address: 'Gaur, Rautahat',
    municipality: 'Gaur',
    district: 'Rautahat',
    province: 'Madhesh',
    latitude: 26.9667,
    longitude: 85.2765,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Mahottari District Hospital',
    address: 'Jaleshwar, Mahottari',
    municipality: 'Jaleshwar',
    district: 'Mahottari',
    province: 'Madhesh',
    latitude: 26.6436,
    longitude: 85.7977,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Sarlahi District Hospital',
    address: 'Malangwa, Sarlahi',
    municipality: 'Malangwa',
    district: 'Sarlahi',
    province: 'Madhesh',
    latitude: 26.8593,
    longitude: 85.5635,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Bara District Hospital',
    address: 'Kalaiya, Bara',
    municipality: 'Kalaiya',
    district: 'Bara',
    province: 'Madhesh',
    latitude: 27.0323,
    longitude: 85.0000,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Udayapur District Hospital',
    address: 'Gaighat, Udayapur',
    municipality: 'Gaighat',
    district: 'Udayapur',
    province: 'Madhesh',
    latitude: 26.9965,
    longitude: 86.9838,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dhanusa District Hospital',
    address: 'Janakpur, Dhanusha',
    municipality: 'Janakpur',
    district: 'Dhanusha',
    province: 'Madhesh',
    latitude: 26.7289,
    longitude: 85.9243,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== GANDAKI PROVINCE (8 centers) ====================
  {
    name: 'Pokhara Academy of Health Sciences (PAHS)',
    address: 'Pokhara, Kaski',
    municipality: 'Pokhara',
    district: 'Kaski',
    province: 'Gandaki',
    latitude: 28.2096,
    longitude: 83.9856,
    phone: '061-504048',
    emergencyPhone: '061-504048',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Gandaki Medical College',
    address: 'Pokhara, Kaski',
    municipality: 'Pokhara',
    district: 'Kaski',
    province: 'Gandaki',
    latitude: 28.2284,
    longitude: 83.9835,
    phone: '061-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
  },
  {
    name: 'Gorkha District Hospital',
    address: 'Gorkha',
    municipality: 'Gorkha',
    district: 'Gorkha',
    province: 'Gandaki',
    latitude: 28.2667,
    longitude: 84.6333,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Lamjung District Hospital',
    address: 'Besisahar, Lamjung',
    municipality: 'Besisahar',
    district: 'Lamjung',
    province: 'Gandaki',
    latitude: 28.2331,
    longitude: 84.4179,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Tanahun District Hospital',
    address: 'Damauli, Tanahun',
    municipality: 'Damauli',
    district: 'Tanahun',
    province: 'Gandaki',
    latitude: 27.9558,
    longitude: 84.2862,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Syangja District Hospital',
    address: 'Syangja',
    municipality: 'Syangja',
    district: 'Syangja',
    province: 'Gandaki',
    latitude: 27.9667,
    longitude: 83.8833,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Baglung District Hospital',
    address: 'Baglung',
    municipality: 'Baglung',
    district: 'Baglung',
    province: 'Gandaki',
    latitude: 28.2667,
    longitude: 83.6000,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Parbat District Hospital',
    address: 'Kushma, Parbat',
    municipality: 'Kushma',
    district: 'Parbat',
    province: 'Gandaki',
    latitude: 28.2146,
    longitude: 83.6964,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== LUMBINI PROVINCE (14 centers) ====================
  // Rupandehi District - High snakebite incidence area
  {
    name: 'Lumbini Provincial Hospital',
    address: 'Butwal-11, Rupandehi',
    municipality: 'Butwal',
    ward: 11,
    district: 'Rupandehi',
    province: 'Lumbini',
    latitude: 27.6978,
    longitude: 83.4642,
    phone: '071-540333',
    emergencyPhone: '071-540333',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'PROVINCIAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
    notes: 'Provincial referral center for snakebite cases. Call to confirm current antivenom availability.',
  },
  {
    name: 'Bhim Hospital',
    address: 'Bhairahawa-03, Rupandehi',
    municipality: 'Siddharthanagar',
    ward: 3,
    district: 'Rupandehi',
    province: 'Lumbini',
    latitude: 27.5051,
    longitude: 83.4533,
    phone: '071-521321',
    emergencyPhone: '071-521321',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'PRIVATE',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Local_Health_Facilities',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
    notes: 'Major private hospital in Bhairahawa. Known for emergency trauma care. Call to confirm antivenom stock.',
  },
  {
    name: 'Universal College of Medical Sciences (UCMS)',
    address: 'Bhairahawa-05, Rupandehi',
    municipality: 'Siddharthanagar',
    ward: 5,
    district: 'Rupandehi',
    province: 'Lumbini',
    latitude: 27.5089,
    longitude: 83.4604,
    phone: '071-520295',
    emergencyPhone: '071-520295',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'REFERRAL',
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    source: 'Local_Health_Facilities',
    sourceYear: '2081/82',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
    notes: 'Teaching hospital with emergency medicine department. Handles critical snakebite cases. Call to verify antivenom availability.',
  },
  {
    name: 'Lumbini Medical College',
    address: 'Palpa',
    municipality: 'Tansen',
    district: 'Palpa',
    province: 'Lumbini',
    latitude: 27.8667,
    longitude: 83.5500,
    phone: '075-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    antivenomStatus: 'AVAILABLE',
    ventilatorAvailable: true,
    icuAvailable: true,
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'PRIVATE',
    status: 'ACTIVE',
  },
  {
    name: 'Kapilvastu District Hospital',
    address: 'Taulihawa, Kapilvastu',
    municipality: 'Taulihawa',
    district: 'Kapilvastu',
    province: 'Lumbini',
    latitude: 27.5436,
    longitude: 83.0552,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Nawalparasi District Hospital',
    address: 'Ramgram, Nawalparasi',
    municipality: 'Ramgram',
    district: 'Nawalparasi',
    province: 'Lumbini',
    latitude: 27.6267,
    longitude: 84.0333,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Arghakhanchi District Hospital',
    address: 'Sandhikharka, Arghakhanchi',
    municipality: 'Sandhikharka',
    district: 'Arghakhanchi',
    province: 'Lumbini',
    latitude: 27.9181,
    longitude: 83.1794,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Gulmi District Hospital',
    address: 'Tamghas, Gulmi',
    municipality: 'Tamghas',
    district: 'Gulmi',
    province: 'Lumbini',
    latitude: 28.0833,
    longitude: 83.2833,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Pyuthan District Hospital',
    address: 'Pyuthan',
    municipality: 'Pyuthan',
    district: 'Pyuthan',
    province: 'Lumbini',
    latitude: 28.0942,
    longitude: 82.8667,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Rolpa District Hospital',
    address: 'Libang, Rolpa',
    municipality: 'Libang',
    district: 'Rolpa',
    province: 'Lumbini',
    latitude: 28.3125,
    longitude: 82.6306,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dang District Hospital',
    address: 'Ghorahi, Dang',
    municipality: 'Ghorahi',
    district: 'Dang',
    province: 'Lumbini',
    latitude: 28.0313,
    longitude: 82.4878,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Banke District Hospital',
    address: 'Nepalgunj, Banke',
    municipality: 'Nepalgunj',
    district: 'Banke',
    province: 'Lumbini',
    latitude: 28.0500,
    longitude: 81.6167,
    phone: '081-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Bardiya District Hospital',
    address: 'Gulariya, Bardiya',
    municipality: 'Gulariya',
    district: 'Bardiya',
    province: 'Lumbini',
    latitude: 28.2044,
    longitude: 81.3528,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== KARNALI PROVINCE (6 centers) ====================
  {
    name: 'Surkhet Provincial Hospital',
    address: 'Birendranagar, Surkhet',
    municipality: 'Birendranagar',
    district: 'Surkhet',
    province: 'Karnali',
    latitude: 28.6000,
    longitude: 81.6333,
    phone: '083-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dailekh District Hospital',
    address: 'Dailekh',
    municipality: 'Dailekh',
    district: 'Dailekh',
    province: 'Karnali',
    latitude: 28.8500,
    longitude: 81.7167,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Jajarkot District Hospital',
    address: 'Jajarkot',
    municipality: 'Jajarkot',
    district: 'Jajarkot',
    province: 'Karnali',
    latitude: 28.6900,
    longitude: 82.1900,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Salyan District Hospital',
    address: 'Salyan',
    municipality: 'Salyan',
    district: 'Salyan',
    province: 'Karnali',
    latitude: 28.3667,
    longitude: 82.1667,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Jumla District Hospital',
    address: 'Jumla',
    municipality: 'Jumla',
    district: 'Jumla',
    province: 'Karnali',
    latitude: 29.2736,
    longitude: 82.1833,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Mugu District Hospital',
    address: 'Gamgadhi, Mugu',
    municipality: 'Gamgadhi',
    district: 'Mugu',
    province: 'Karnali',
    latitude: 29.6833,
    longitude: 82.1500,
    emergencyAvailable: false,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },

  // ==================== SUDURPASCHIM PROVINCE (7 centers) ====================
  {
    name: 'Seti Provincial Hospital',
    address: 'Dhangadhi, Kailali',
    municipality: 'Dhangadhi',
    district: 'Kailali',
    province: 'Sudurpaschim',
    latitude: 28.6969,
    longitude: 80.5894,
    phone: '091-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Mahakali Zonal Hospital',
    address: 'Mahendranagar, Kanchanpur',
    municipality: 'Mahendranagar',
    district: 'Kanchanpur',
    province: 'Sudurpaschim',
    latitude: 28.9667,
    longitude: 80.1833,
    phone: '099-520111',
    emergencyAvailable: true,
    emergency24x7: true,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Doti District Hospital',
    address: 'Dipayal, Doti',
    municipality: 'Dipayal',
    district: 'Doti',
    province: 'Sudurpaschim',
    latitude: 29.2667,
    longitude: 80.9500,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Dadeldhura District Hospital',
    address: 'Dadeldhura',
    municipality: 'Dadeldhura',
    district: 'Dadeldhura',
    province: 'Sudurpaschim',
    latitude: 29.3000,
    longitude: 80.5833,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Baitadi District Hospital',
    address: 'Baitadi',
    municipality: 'Baitadi',
    district: 'Baitadi',
    province: 'Sudurpaschim',
    latitude: 29.5333,
    longitude: 80.5500,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Achham District Hospital',
    address: 'Mangalsen, Achham',
    municipality: 'Mangalsen',
    district: 'Achham',
    province: 'Sudurpaschim',
    latitude: 29.1333,
    longitude: 81.1333,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
  {
    name: 'Bajhang District Hospital',
    address: 'Chainpur, Bajhang',
    municipality: 'Chainpur',
    district: 'Bajhang',
    province: 'Sudurpaschim',
    latitude: 29.5500,
    longitude: 81.2167,
    emergencyAvailable: true,
    emergency24x7: false,
    snakebiteTreatmentAvailable: true,
    treatmentCenterType: 'DISTRICT',
    antivenomStatus: 'AVAILABLE',
    source: 'EDCD',
    sourceYear: '2078/79',
    officialTreatmentCenter: true,
    verificationStatus: 'HISTORICAL',
    hospitalType: 'GOVERNMENT',
    status: 'ACTIVE',
  },
];

async function seedHospitals() {
  console.log('🏥 Starting hospital seed...');

  let created = 0;
  let skipped = 0;

  for (const hospital of hospitals) {
    try {
      // Check if hospital already exists
      const existing = await (prisma.hospital.findFirst as any)({
        where: {
          name: hospital.name,
          district: hospital.district,
        },
      });

      if (existing) {
        console.log(`⏭️  Skipping ${hospital.name} (already exists)`);
        skipped++;
        continue;
      }

      // Create hospital
      await (prisma.hospital.create as any)({
        data: hospital as any,
      });

      console.log(`✅ Created ${hospital.name}`);
      created++;

      // Add verification record for verified hospitals
      if (hospital.verificationStatus === 'VERIFIED') {
        await (prisma.hospitalVerification.create as any)({
          data: {
            hospitalId: (await (prisma.hospital.findFirst as any)({
              where: { name: hospital.name },
              select: { id: true },
            }))!.id,
            verifiedBy: 'SYSTEM_SEED',
            verificationType: 'OFFICIAL_DOCUMENT',
            snakebiteTreatment: hospital.snakebiteTreatmentAvailable,
            antivenomStatus: hospital.antivenomStatus as any,
            emergencyStatus: hospital.emergency24x7,
            ventilatorStatus: hospital.ventilatorAvailable,
            notes: `Initial verification from ${hospital.source} (${hospital.sourceYear})`,
            verificationDate: new Date(),
          },
        });
        console.log(`  ✓ Added verification record`);
      }
    } catch (error) {
      console.error(`❌ Error creating ${hospital.name}:`, error);
    }
  }

  console.log('\n📊 Seed Summary:');
  console.log(`   Created: ${created} hospitals`);
  console.log(`   Skipped: ${skipped} hospitals (already exist)`);
  console.log(`   Total: ${hospitals.length} hospitals processed`);
}

// Export the function so it can be used by seed-full.ts
export { seedHospitals };

async function main() {
  try {
    await seedHospitals();
    console.log('\n✅ Hospital seed completed successfully!');
  } catch (error) {
    console.error('❌ Hospital seed failed:', error);
    throw error;
  }
}

// Only run main() if this file is executed directly (not imported)
if (import.meta.url === `file://${process.argv[1].replace(/\\/g, '/')}`) {
  main()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
