// ===================================================================
// GRAPHQL TYPES - TypeScript Definitions
// ===================================================================
// These types will be auto-generated by GraphQL Code Generator
// This file serves as a placeholder and re-export point
// ===================================================================

// These types will be generated by running:
// yarn graphql:codegen

// For now, we export the schema location
export const GRAPHQL_SCHEMA_PATH = './schema.graphql';

// Placeholder exports (will be replaced by codegen)
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
